### PR TITLE
Adding torch to setup.cfg

### PR DESCRIPTION
**Pull request by beniroquai**

### CODE REVIEW

**Review by andreabassi78 — APPROVED** [review]

**Comment by pptman** [comment]
Actually fiftw might also be a valid requirement if torch and cupy are.  Fftw is used if available instead of numpy fft routines.

**Comment by andreabassi78** [comment]
Good point @pptman. The code [tries importing torch, cupy, pyfft ](https://github.com/andreabassi78/napari-sim-processor/blob/a84d34d272c2c20b18d8c242539c04c1e8c92840/src/napari_sim_processor/baseSimProcessor.py#L8-L43), and uses numpy in case of exception. This makes the modules optional.
We could probably go back to the previous version, but I double-check with @beniroquai whether he sees any shortcomings. Thanks for reviewing the code btw.

**Comment by beniroquai** [comment]
Thanks! When going though the code it becomes more obvious that I don't need pytorch to get it working. However, I couldn'T get it working in the first place; The Napari Plugin kept crashing. With installing pytorch, it worked :)

**Comment by pptman** [comment]
I have no problem running the plugin when I uninstall torch.  Do you recall where it was crashing?  Was this the pypl version or the most recent GitHub version?

**Comment by andreabassi78** [comment]
I reopen this discussion. Please notify us here if you have any problems using the plugin without having torch or cupy installed.

**Pull request merged**
